apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mks-bank
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine   # alpine = smaller image (~30MB vs ~100MB)
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          # Redis health check using the redis-cli PING command
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
