sonar.projectKey=mks-bank-backend
sonar.projectName=MKS Bank Backend
sonar.projectVersion=1.0

# Path to source directories 
sonar.sources=src/main/java

# Path to test directories (if any)
sonar.tests=src/test/java

# Path to compiled classes
sonar.java.binaries=target/classes

# Language
sonar.language=java

# Encoding
sonar.sourceEncoding=UTF-8
