apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: mks-bank
  labels:
    app: postgres
spec:
  # "docker.io/hostpath" is the default StorageClass for Docker Desktop on Windows
  # It stores data in the Docker Desktop VM's filesystem
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce   # Only one pod can write at a time (correct for a single DB)
  resources:
    requests:
      storage: 1Gi    # 1 GB of persistent storage for the database
